# docker run --detach --name some-mariadb --env MARIADB_USER=maria --env MARIADB_PASSWORD=maria.123 --env MARIADB_RANDOM_ROOT_PASSWORD=yes --env MARIADB_DATABASE=maria -p 3306:3306 mariadb:latest
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/maria
    username: maria
    password: maria.123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
